import { useState, useEffect } from "react";
import { Zap, AlertTriangle, TrendingUp, Cpu, Bot, CheckCircle, RefreshCw, BarChart2 } from "lucide-react";
import { ForecastCardData } from "../types";

interface ForecastingViewProps {
  forecasts: ForecastCardData[];
  openExplainModal: (title: string, content: string) => void;
}

export default function ForecastingView({ forecasts, openExplainModal }: ForecastingViewProps) {
  const [aiInsights, setAiInsights] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [insightModel, setInsightModel] = useState("");

  const fetchAiInsights = async () => {
    setIsLoading(true);
    try {
      const response = await fetch("/api/ai/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          flareClass: "C1.45",
          riskScore: 42,
          confidence: 94.6,
          activeFlares: 3,
          detectorStatus: "SoLEXS-A & HEL1OS CZT Nominal",
        }),
      });
      const data = await response.json();
      if (data.insights) {
        setAiInsights(data.insights);
        setInsightModel(data.model || "Gemini-3.5-Flash");
      }
    } catch (e) {
      console.error("Error retrieving AI insights:", e);
      // Fallback local rules
      setAiInsights([
        "**Magnetic Heating Phase**: Background Soft X-ray flux stabilized at C1.45 indicates persistent thermal heating of active coronal loops, primarily driven by localized flux emergence in Active Region AR3712.",
        "**Reconnection Risk Low-Moderate**: Current Risk Score of 42/100 and system confidence of 94.6% indicates moderate magnetic shear. No immediate imminent X-class triggers detected, though minor impulsive micro-flares remain highly probable.",
        "**Operational Posture Level - Green**: Recommend normal operating configurations for low-Earth orbit (LEO) satellites. Continue monitoring high-energy CdTe pixel arrays on HEL1OS for impulsive hard X-ray signatures.",
      ]);
      setInsightModel("Local Physics Rules Engine (Fallback)");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAiInsights();
  }, []);

  return (
    <div className="space-y-6 animate-fade-in" id="forecasting-view">
      {/* Page Title */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
        <div>
          <span className="text-[10px] font-bold text-gray-400 font-mono uppercase tracking-wider">
            ADITYA-L1 MACHINE LEARNING CORE
          </span>
          <h2 className="text-xl font-bold text-gray-900 mt-0.5">Solar Flare Probability Forecasting</h2>
          <p className="text-xs text-gray-500 mt-1">
            Predictive probability cards and explainable AI insights spanning various orbital lead times.
          </p>
        </div>

        <button
          onClick={fetchAiInsights}
          disabled={isLoading}
          className="flex items-center space-x-2 rounded-lg bg-[#0057B8] px-4 py-2 text-xs font-semibold text-white shadow-sm hover:bg-opacity-90 transition disabled:opacity-50"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${isLoading ? "animate-spin" : ""}`} />
          <span>{isLoading ? "Analyzing..." : "Re-Run Prediction Models"}</span>
        </button>
      </div>

      {/* Predictions Cards Grid */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {forecasts.map((card, idx) => {
          // Determine styling based on probability level
          let levelBg = "bg-green-50 border-green-100 text-green-700";
          let probColor = "text-gray-900";

          if (card.probability > 75) {
            levelBg = "bg-red-50 border-red-100 text-red-700";
            probColor = "text-[#DC2626]";
          } else if (card.probability > 40) {
            levelBg = "bg-amber-50 border-amber-100 text-amber-700";
            probColor = "text-[#F57C00]";
          }

          return (
            <div
              key={idx}
              onClick={() =>
                openExplainModal(
                  `${card.timeframe} Flare Forecast Breakdown`,
                  `This forecast has been generated by the Aditya-L1 Multi-layer Convolutional Neural Network. Key contributing factors for this lead time include:\n\n` +
                    card.factors.map((f) => `- ${f}`).join("\n") +
                    `\n\nModel validation indicates an operational precision score of ${card.confidence}% at this horizon.`
                )
              }
              className="group cursor-pointer rounded-xl border border-gray-200 bg-white p-5 shadow-sm transition hover:border-[#0057B8] hover:shadow"
            >
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-gray-400 font-mono uppercase tracking-wider">
                  Lead Time: {card.timeframe}
                </span>
                <TrendingUp className="h-4.5 w-4.5 text-gray-400 group-hover:text-[#0057B8]" />
              </div>

              <div className="mt-4">
                <span className="block text-[10px] font-bold text-gray-400 font-mono uppercase">PROBABILITY</span>
                <span className={`text-4xl font-extrabold font-mono tracking-tight ${probColor}`}>
                  {card.probability.toFixed(1)}%
                </span>
              </div>

              <div className="mt-4 grid grid-cols-2 gap-2 border-t border-gray-100 pt-3 text-[10px] font-mono">
                <div>
                  <span className="block text-gray-400 font-semibold uppercase">Confidence</span>
                  <span className="font-bold text-gray-700">{card.confidence}%</span>
                </div>
                <div>
                  <span className="block text-gray-400 font-semibold uppercase">Expected Class</span>
                  <span className="font-bold text-gray-800">{card.expectedClass}</span>
                </div>
              </div>

              {/* Progress bar representing probability */}
              <div className="mt-4 h-1.5 w-full bg-gray-100 rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full ${
                    card.probability > 75 ? "bg-[#DC2626]" : card.probability > 40 ? "bg-[#F57C00]" : "bg-[#16A34A]"
                  }`}
                  style={{ width: `${card.probability}%` }}
                ></div>
              </div>
            </div>
          );
        })}
      </div>

      {/* AI Insights & Contributions Grid */}
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* Explainable AI & Scientific Interpretation */}
        <div className="lg:col-span-2 rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between border-b border-gray-100 pb-3 mb-4">
            <div className="flex items-center space-x-2">
              <Bot className="h-5 w-5 text-[#0057B8]" />
              <h3 className="text-base font-bold text-gray-900">Explainable AI (XAI) Scientific Interpretations</h3>
            </div>
            {insightModel && (
              <span className="rounded bg-[#F7F9FC] border border-gray-100 px-2.5 py-0.5 text-[9px] font-mono font-bold text-gray-500 uppercase">
                ENGINE: {insightModel}
              </span>
            )}
          </div>

          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-12 space-y-3">
              <RefreshCw className="h-8 w-8 text-[#0057B8] animate-spin" />
              <p className="text-xs text-gray-500 font-mono font-semibold">Running multi-instrument observation synthesis...</p>
            </div>
          ) : (
            <div className="space-y-4">
              {aiInsights.map((insight, idx) => {
                // Formatting markdown highlights safely
                const parts = insight.split("**");
                return (
                  <div key={idx} className="rounded-lg bg-[#F7F9FC] border border-gray-100 p-4 leading-normal text-xs text-gray-600">
                    {parts.map((part, pIdx) => {
                      if (pIdx % 2 === 1) {
                        return <strong key={pIdx} className="text-gray-900 font-semibold">{part}</strong>;
                      }
                      return part;
                    })}
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Neural Network Contributing Factors (Feature Importance) */}
        <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <h3 className="text-base font-bold text-gray-900 flex items-center space-x-2">
            <BarChart2 className="h-5 w-5 text-[#F57C00]" />
            <span>Feature Importance Weighting</span>
          </h3>
          <p className="text-xs text-gray-500 mt-0.5">Top physics parameters contributing to the neural network weights.</p>

          <div className="mt-6 space-y-4">
            {/* Factor 1 */}
            <div className="space-y-1">
              <div className="flex justify-between text-xs font-mono font-semibold">
                <span className="text-gray-700">Soft X-Ray Flux Gradient (dFlux/dt)</span>
                <span className="text-gray-900">42.5%</span>
              </div>
              <div className="h-2 w-full bg-gray-100 rounded-full overflow-hidden">
                <div className="h-full bg-[#0057B8] rounded-full" style={{ width: "42.5%" }}></div>
              </div>
            </div>

            {/* Factor 2 */}
            <div className="space-y-1">
              <div className="flex justify-between text-xs font-mono font-semibold">
                <span className="text-gray-700">Active Region Magnetic Helicity index</span>
                <span className="text-gray-900">24.1%</span>
              </div>
              <div className="h-2 w-full bg-gray-100 rounded-full overflow-hidden">
                <div className="h-full bg-[#0057B8] rounded-full" style={{ width: "24.1%" }}></div>
              </div>
            </div>

            {/* Factor 3 */}
            <div className="space-y-1">
              <div className="flex justify-between text-xs font-mono font-semibold">
                <span className="text-gray-700">HEL1OS Hard X-ray Spectral Index</span>
                <span className="text-gray-900">18.4%</span>
              </div>
              <div className="h-2 w-full bg-gray-100 rounded-full overflow-hidden">
                <div className="h-full bg-[#0057B8] rounded-full" style={{ width: "18.4%" }}></div>
              </div>
            </div>

            {/* Factor 4 */}
            <div className="space-y-1">
              <div className="flex justify-between text-xs font-mono font-semibold">
                <span className="text-gray-700">Active Region Area Expansion Rate</span>
                <span className="text-gray-900">10.2%</span>
              </div>
              <div className="h-2 w-full bg-gray-100 rounded-full overflow-hidden">
                <div className="h-full bg-[#0057B8] rounded-full" style={{ width: "10.2%" }}></div>
              </div>
            </div>

            {/* Factor 5 */}
            <div className="space-y-1">
              <div className="flex justify-between text-xs font-mono font-semibold">
                <span className="text-gray-700">Spacecraft Coronal Alignment Quality</span>
                <span className="text-gray-900">4.8%</span>
              </div>
              <div className="h-2 w-full bg-gray-100 rounded-full overflow-hidden">
                <div className="h-full bg-[#0057B8] rounded-full" style={{ width: "4.8%" }}></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
